[build]
  command = "hugo"
  publish = "public"
[build.environment]
  HUGO_VERSION = "0.128.0"
  NODE_VERSION = "22"

[context.branch-deploy]
  command = "hugo -F -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
  command = "hugo -F -b $DEPLOY_PRIME_URL"

[context.production.environment]
  HUGO_ENV = "production"
